
basketball_glossary = [
    "Baloncesto",
     "Euroliga",
     "Equipo",
     "Partido",
     "Liga",
     "NBA",
     "Jugador",
     "Victoria",
     "Canasta",
     "Jornada",
     "Entrenador",
     "ACB",
     "Derrota",
     "Prórroga",
     "Tiempo muerto"]

cinema_glossary = [
    "Película",
    "Historia",
    "Director",
    "Interprete",
    "Personaje",
    "Actriz",
    "Festival",
    "Protagonista",
    "Actor",
    "Guión",
    "Crítica",
    "Productor",
    "Actor secundario",
    "Actriz secundaria",
    "Recaudación"]

pollution_glossary = [
    "Atmósfera",
    "Cielo",
    "Energía",
    "Lluvia",
    "Planeta",
    "Tierra",
    "Ciencia",
    "Partícula",
    "Aire",
    "Científico",
    "Investigación",
    "Salud",
    "Calidad del aire",
    "Medio ambiente",
    "Calentamiento global"]
